# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/bengal/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter citrus lime,$(TARGET_DEVICE)),)

endif
